use_frameworks!

platform :ios, '8.0'

target 'JySignaturePanel_Example' do
  pod 'Masonry', '~> 1.1.0'
  pod 'Toast', '~> 4.0.0'
  pod 'JySignaturePanel', :path => '../'

  target 'JySignaturePanel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
